//! Short-lived, capability-safe media hosting for Telegram guest-result edits.
//!
//! Telegram cannot accept a newly uploaded file while editing an inline/guest
//! result, but it can fetch an HTTPS URL. Generated bytes are therefore exposed
//! under an unguessable token for ten minutes and are never persisted to disk.

use std::{
    collections::HashMap,
    sync::{Arc, LazyLock, RwLock},
    time::{Duration, Instant},
};

use axum::{
    body::Body,
    extract::Path,
    http::{HeaderMap, HeaderValue, Method, Response, StatusCode, header},
};
use uuid::Uuid;

use crate::Result;
use eyre::bail;

const TTL: Duration = Duration::from_secs(10 * 60);
const MAX_ITEM_BYTES: usize = 50 * 1024 * 1024;
const MAX_TOTAL_BYTES: usize = 128 * 1024 * 1024;
static MEDIA: LazyLock<RwLock<HashMap<String, HostedMedia>>> =
    LazyLock::new(|| RwLock::new(HashMap::new()));

struct HostedMedia {
    bytes: Arc<Vec<u8>>,
    content_type: String,
    filename: Option<String>,
    expires: Instant,
}

/// Publishes bytes at a cryptographically unguessable token and returns it.
pub fn publish(bytes: Vec<u8>, content_type: impl Into<String>) -> Result<String> {
    publish_inner(bytes, content_type.into(), None)
}

/// Publishes a generated document while preserving a safe download filename.
pub fn publish_named(
    bytes: Vec<u8>,
    content_type: impl Into<String>,
    filename: &str,
) -> Result<String> {
    let filename = filename
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || matches!(character, '.' | '-' | '_') {
                character
            } else {
                '_'
            }
        })
        .collect::<String>();
    publish_inner(bytes, content_type.into(), Some(filename))
}

fn publish_inner(bytes: Vec<u8>, content_type: String, filename: Option<String>) -> Result<String> {
    if bytes.is_empty() || bytes.len() > MAX_ITEM_BYTES {
        bail!("Generated guest media must be between 1 byte and 50 MiB");
    }
    let extension = filename
        .as_deref()
        .and_then(|name| name.rsplit_once('.').map(|(_, extension)| extension))
        .filter(|extension| {
            !extension.is_empty()
                && extension.len() <= 12
                && extension
                    .chars()
                    .all(|character| character.is_ascii_alphanumeric())
        })
        .unwrap_or_else(|| extension_for_content_type(&content_type));
    let token = format!("{}.{extension}", Uuid::now_v7());
    let mut media = MEDIA.write().expect("ephemeral media lock poisoned");
    media.retain(|_, item| item.expires > Instant::now());
    while media.values().map(|item| item.bytes.len()).sum::<usize>() + bytes.len() > MAX_TOTAL_BYTES
    {
        let Some(oldest) = media
            .iter()
            .min_by_key(|(_, item)| item.expires)
            .map(|(token, _)| token.clone())
        else {
            break;
        };
        media.remove(&oldest);
    }
    media.insert(
        token.clone(),
        HostedMedia {
            bytes: Arc::new(bytes),
            content_type,
            filename,
            expires: Instant::now() + TTL,
        },
    );
    Ok(token)
}

/// Serves a short-lived generated asset with byte-range support for Telegram.
pub async fn serve(
    Path(token): Path<String>,
    method: Method,
    request_headers: HeaderMap,
) -> Response<Body> {
    let item = MEDIA
        .read()
        .expect("ephemeral media lock poisoned")
        .get(&token)
        .filter(|item| item.expires > Instant::now())
        .map(|item| {
            (
                item.bytes.clone(),
                item.content_type.clone(),
                item.filename.clone(),
            )
        });
    let Some((bytes, content_type, filename)) = item else {
        return Response::builder()
            .status(StatusCode::NOT_FOUND)
            .body(Body::empty())
            .expect("static response");
    };
    let total = bytes.len();
    let range = request_headers
        .get(header::RANGE)
        .and_then(|value| value.to_str().ok())
        .and_then(|value| parse_range(value, total));
    let (status, start, end) = range.map_or((StatusCode::OK, 0, total), |(start, end)| {
        (StatusCode::PARTIAL_CONTENT, start, end)
    });
    let body = if method == Method::HEAD {
        Body::empty()
    } else {
        Body::from(bytes[start..end].to_vec())
    };
    let mut response = Response::new(body);
    *response.status_mut() = status;
    response.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_str(&content_type)
            .unwrap_or_else(|_| HeaderValue::from_static("application/octet-stream")),
    );
    if let Some(filename) = filename
        && let Ok(value) = HeaderValue::from_str(&format!("attachment; filename=\"{filename}\""))
    {
        response
            .headers_mut()
            .insert(header::CONTENT_DISPOSITION, value);
    }
    response.headers_mut().insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=600, immutable"),
    );
    response
        .headers_mut()
        .insert(header::ACCEPT_RANGES, HeaderValue::from_static("bytes"));
    if let Ok(value) = HeaderValue::from_str(&(end - start).to_string()) {
        response.headers_mut().insert(header::CONTENT_LENGTH, value);
    }
    if status == StatusCode::PARTIAL_CONTENT
        && let Ok(value) = HeaderValue::from_str(&format!("bytes {start}-{}/{total}", end - 1))
    {
        response.headers_mut().insert(header::CONTENT_RANGE, value);
    }
    response.headers_mut().insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    response
}

fn extension_for_content_type(content_type: &str) -> &'static str {
    match content_type.split(';').next().unwrap_or_default().trim() {
        "image/png" => "png",
        "image/jpeg" => "jpg",
        "image/webp" => "webp",
        "image/gif" => "gif",
        "audio/mpeg" => "mp3",
        "audio/ogg" => "ogg",
        "audio/wav" | "audio/x-wav" => "wav",
        "video/webm" => "webm",
        "video/quicktime" => "mov",
        "video/mp4" => "mp4",
        "application/pdf" => "pdf",
        _ => "bin",
    }
}

fn parse_range(value: &str, total: usize) -> Option<(usize, usize)> {
    let value = value.strip_prefix("bytes=")?;
    if value.contains(',') || total == 0 {
        return None;
    }
    let (start, end) = value.split_once('-')?;
    let start = start.parse::<usize>().ok()?;
    let end = if end.is_empty() {
        total
    } else {
        end.parse::<usize>().ok()?.checked_add(1)?.min(total)
    };
    (start < end && start < total).then_some((start, end))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hosted_tokens_have_media_extensions_and_ranges_are_bounded() {
        let token = publish(vec![1, 2, 3], "image/png").unwrap();
        assert!(token.ends_with(".png"));
        let id = token.strip_suffix(".png").unwrap().parse::<Uuid>().unwrap();
        assert_eq!(id.get_version_num(), 7);
        assert_eq!(parse_range("bytes=0-0", 3), Some((0, 1)));
        assert_eq!(parse_range("bytes=1-", 3), Some((1, 3)));
        assert_eq!(parse_range("bytes=3-4", 3), None);
        assert_eq!(parse_range("bytes=0-1,2-2", 3), None);
    }

    #[test]
    fn named_documents_preserve_their_safe_extension() {
        let token = publish_named(vec![1, 2, 3], "text/html", "index.html").unwrap();
        assert!(token.ends_with(".html"));
    }
}
