//! Short-lived, capability-safe media hosting for Telegram guest-result edits.
//!
//! Telegram cannot accept a newly uploaded file while editing an inline/guest
//! result, but it can fetch an HTTPS URL. Generated bytes are therefore exposed
//! under an unguessable token for ten minutes and are never persisted to disk.

use std::{
    collections::HashMap,
    sync::{Arc, LazyLock, RwLock},
    time::{Duration, Instant},
};

use axum::{
    body::Body,
    extract::Path,
    http::{HeaderValue, Response, StatusCode, header},
};
use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use rand::RngExt;

use crate::Result;
use eyre::bail;

const TTL: Duration = Duration::from_secs(10 * 60);
const MAX_ITEM_BYTES: usize = 50 * 1024 * 1024;
const MAX_TOTAL_BYTES: usize = 128 * 1024 * 1024;
static MEDIA: LazyLock<RwLock<HashMap<String, HostedMedia>>> =
    LazyLock::new(|| RwLock::new(HashMap::new()));

struct HostedMedia {
    bytes: Arc<Vec<u8>>,
    content_type: String,
    expires: Instant,
}

/// Publishes bytes at a cryptographically unguessable token and returns it.
pub fn publish(bytes: Vec<u8>, content_type: impl Into<String>) -> Result<String> {
    if bytes.is_empty() || bytes.len() > MAX_ITEM_BYTES {
        bail!("Generated guest media must be between 1 byte and 50 MiB");
    }
    let mut random = [0_u8; 32];
    rand::rng().fill(&mut random);
    let token = URL_SAFE_NO_PAD.encode(random);
    let mut media = MEDIA.write().expect("ephemeral media lock poisoned");
    media.retain(|_, item| item.expires > Instant::now());
    while media.values().map(|item| item.bytes.len()).sum::<usize>() + bytes.len() > MAX_TOTAL_BYTES
    {
        let Some(oldest) = media
            .iter()
            .min_by_key(|(_, item)| item.expires)
            .map(|(token, _)| token.clone())
        else {
            break;
        };
        media.remove(&oldest);
    }
    media.insert(
        token.clone(),
        HostedMedia {
            bytes: Arc::new(bytes),
            content_type: content_type.into(),
            expires: Instant::now() + TTL,
        },
    );
    Ok(token)
}

/// Serves a non-cacheable generated asset to Telegram's media fetcher.
pub async fn serve(Path(token): Path<String>) -> Response<Body> {
    let item = MEDIA
        .read()
        .expect("ephemeral media lock poisoned")
        .get(&token)
        .filter(|item| item.expires > Instant::now())
        .map(|item| (item.bytes.clone(), item.content_type.clone()));
    let Some((bytes, content_type)) = item else {
        return Response::builder()
            .status(StatusCode::NOT_FOUND)
            .body(Body::empty())
            .expect("static response");
    };
    let mut response = Response::new(Body::from(bytes.as_ref().clone()));
    response.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_str(&content_type)
            .unwrap_or_else(|_| HeaderValue::from_static("application/octet-stream")),
    );
    response.headers_mut().insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("private, max-age=600"),
    );
    response.headers_mut().insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    response
}
